# Site settings
title: Andy Mehalick
email: andy.mehalick@orangejetpack.com
description: A software development process and technology blog; a look at the tools and techniques for building better software.
baseurl: ""
url: https://andy.mehalick.com
imge: https://az808808.vo.msecnd.net/assets/andy-mehalick-v1-280x280-635783259977684363.jpg
twitter_username: andymehalick
github_username: andy-mehalick
google_plus: https://plus.google.com/113902592100905338618

# Build settings
markdown: kramdown
highlighter: rouge

# Outputting
permalink: /:year/:month/:day/:title/